#!/usr/bin/env node

import fs = require("node:fs");
import path = require("node:path");

export interface InitConsumerCliArgs {
  host: string | null;
  outDir: string | null;
  force: boolean;
  help: boolean;
}

interface TemplateHostDefinition {
  canonicalHost: "node" | "python" | "codex";
  sourceDirName: string;
  filenames: string[];
  generatedReadme: string;
}

interface WriteConsumerTemplateResult {
  ok: true;
  host: "node" | "python" | "codex";
  out_dir: string;
  files: string[];
}

const HOST_DEFINITIONS: Record<string, TemplateHostDefinition> = {
  node: {
    canonicalHost: "node",
    sourceDirName: "external-consumer-node",
    filenames: [
      "direct-library-demo.js",
      "cli-subprocess-demo.js",
      "embedded-http-demo.js",
      "pre-action-gate-demo.js",
      "host-router-demo.js"
    ],
    generatedReadme: [
      "# user-habit-pipeline Node Starter",
      "",
      "This folder was generated by `user-habit-pipeline-init-consumer --host node`.",
      "",
      "Files:",
      "",
      "- `direct-library-demo.js`: call the package as a normal Node.js library",
      "- `cli-subprocess-demo.js`: invoke the shipped CLI and read JSON",
      "- `embedded-http-demo.js`: start the official localhost HTTP server from Node.js",
      "- `pre-action-gate-demo.js`: gate a host action before execution with a stable semantic decision object",
      "- `host-router-demo.js`: simulate `interpret -> decide -> route` inside a host-owned routing layer",
      "",
      "## Install",
      "",
      "From the target project root:",
      "",
      "```powershell",
      "npm install user-habit-pipeline",
      "```",
      "",
      "## Run",
      "",
      "```powershell",
      "node .\\direct-library-demo.js",
      "node .\\cli-subprocess-demo.js",
      "node .\\embedded-http-demo.js",
      "node .\\pre-action-gate-demo.js",
      "node .\\host-router-demo.js",
      "```",
      "",
      "## Recommended Use",
      "",
      "- Use `direct-library-demo.js` when the host is already Node.js and you want the smallest integration surface.",
      "- Use `cli-subprocess-demo.js` when you want an explicit JSON subprocess boundary.",
      "- Use `embedded-http-demo.js` when your host prefers a localhost HTTP contract.",
      "- Use `pre-action-gate-demo.js` when your host needs a lightweight semantic gate before running downstream actions.",
      "- Use `host-router-demo.js` when you want a copyable host-side routing pattern after semantic gating.",
      "",
      "## Next Steps",
      "",
      "1. Keep `user-habit-pipeline` installed in the same project root.",
      "2. Copy the file that matches your preferred integration boundary into your real app code.",
      "3. Replace the sample message, scenario, or port with your own host values."
    ].join("\n")
  },
  nodejs: {
    canonicalHost: "node",
    sourceDirName: "external-consumer-node",
    filenames: [
      "direct-library-demo.js",
      "cli-subprocess-demo.js",
      "embedded-http-demo.js",
      "pre-action-gate-demo.js",
      "host-router-demo.js"
    ],
    generatedReadme: ""
  },
  js: {
    canonicalHost: "node",
    sourceDirName: "external-consumer-node",
    filenames: [
      "direct-library-demo.js",
      "cli-subprocess-demo.js",
      "embedded-http-demo.js",
      "pre-action-gate-demo.js",
      "host-router-demo.js"
    ],
    generatedReadme: ""
  },
  codex: {
    canonicalHost: "codex",
    sourceDirName: "current-session-host-node",
    filenames: [
      "scan-current-session-demo.js",
      "apply-first-candidate-demo.js",
      "scan-apply-interpret-demo.js",
      "happy-path-demo.js"
    ],
    generatedReadme: [
      "# user-habit-pipeline Current-Session Host Starter",
      "",
      "This folder was generated by `user-habit-pipeline-init-consumer --host codex`.",
      "",
      "Files:",
      "",
      "- `scan-current-session-demo.js`: pass a visible role-prefixed transcript into `codex-session-habits` and return chat-ready suggestion data",
      "- `apply-first-candidate-demo.js`: confirm the latest cached candidate with a short follow-up request",
      "- `scan-apply-interpret-demo.js`: prove the same shorthand becomes easier to interpret after an explicit current-session apply step",
      "- `happy-path-demo.js`: run the shortest outward-facing story for scan -> apply -> interpretation improvement",
      "",
      "## Install",
      "",
      "From the target project root:",
      "",
      "```powershell",
      "npm install user-habit-pipeline",
      "```",
      "",
      "## Run",
      "",
      "Run the scan first so the latest suggestion snapshot is cached in the package-managed runtime home:",
      "",
      "```powershell",
      "node .\\scan-current-session-demo.js",
      "node .\\apply-first-candidate-demo.js",
      "node .\\scan-apply-interpret-demo.js",
      "node .\\happy-path-demo.js",
      "```",
      "",
      "## Recommended Use",
      "",
      "- Use this starter when your host already has access to visible chat or Codex conversation text.",
      "- Keep transcript gathering on the host side; do not make users locate private thread files on disk.",
      "- Reuse the latest local suggestion cache for short follow-up actions such as `添加第1条`.",
      "- Use `scan-apply-interpret-demo.js` when you want a compact before/after ROI proof instead of only isolated scan/apply steps.",
      "- Use `happy-path-demo.js` when you need one short recording or README demo path.",
      "- For project-local testing or multi-project isolation, set `USER_HABIT_PIPELINE_HOME` to a host-owned runtime directory before running the starter scripts.",
      "",
      "## Next Steps",
      "",
      "1. Replace the sample transcript excerpt with the visible current conversation from your host.",
      "2. Surface `assistant_reply_markdown`, `suggested_follow_ups`, and `next_step_assessment` directly in the UI.",
      "3. Require explicit user confirmation before writing active habit rules."
    ].join("\n")
  },
  "codex-node": {
    canonicalHost: "codex",
    sourceDirName: "current-session-host-node",
    filenames: [
      "scan-current-session-demo.js",
      "apply-first-candidate-demo.js",
      "scan-apply-interpret-demo.js",
      "happy-path-demo.js"
    ],
    generatedReadme: ""
  },
  "current-session-node": {
    canonicalHost: "codex",
    sourceDirName: "current-session-host-node",
    filenames: [
      "scan-current-session-demo.js",
      "apply-first-candidate-demo.js",
      "scan-apply-interpret-demo.js",
      "happy-path-demo.js"
    ],
    generatedReadme: ""
  },
  "chat-host": {
    canonicalHost: "codex",
    sourceDirName: "current-session-host-node",
    filenames: [
      "scan-current-session-demo.js",
      "apply-first-candidate-demo.js",
      "scan-apply-interpret-demo.js",
      "happy-path-demo.js"
    ],
    generatedReadme: ""
  },
  python: {
    canonicalHost: "python",
    sourceDirName: "external-consumer-python",
    filenames: [
      "cli-demo.py",
      "http-client-demo.py"
    ],
    generatedReadme: [
      "# user-habit-pipeline Python Starter",
      "",
      "This folder was generated by `user-habit-pipeline-init-consumer --host python`.",
      "",
      "Files:",
      "",
      "- `cli-demo.py`: call the shipped CLI from Python and parse JSON",
      "- `http-client-demo.py`: call the official localhost HTTP entrypoint from Python",
      "",
      "## Install",
      "",
      "From the target project root:",
      "",
      "```powershell",
      "npm install user-habit-pipeline",
      "```",
      "",
      "## Run",
      "",
      "```powershell",
      "python .\\cli-demo.py",
      "python .\\http-client-demo.py",
      "```",
      "",
      "The HTTP demo expects `user-habit-pipeline-http` to already be running on `http://127.0.0.1:4848`.",
      "",
      "## Recommended Use",
      "",
      "- Use `cli-demo.py` when you want the simplest stable subprocess boundary.",
      "- Use `http-client-demo.py` when another process is already hosting the local HTTP server.",
      "",
      "## Next Steps",
      "",
      "1. Keep `user-habit-pipeline` installed in the same project root.",
      "2. Replace the sample message, scenario, request, or port with your own host values.",
      "3. Wire the script into your application instead of copying interpretation rules by hand."
    ].join("\n")
  },
  py: {
    canonicalHost: "python",
    sourceDirName: "external-consumer-python",
    filenames: [
      "cli-demo.py",
      "http-client-demo.py"
    ],
    generatedReadme: ""
  },
  python3: {
    canonicalHost: "python",
    sourceDirName: "external-consumer-python",
    filenames: [
      "cli-demo.py",
      "http-client-demo.py"
    ],
    generatedReadme: ""
  }
};

function getCanonicalHostDefinition(host: string): TemplateHostDefinition {
  const normalizedHost = host.trim().toLowerCase();
  const definition = HOST_DEFINITIONS[normalizedHost];

  if (!definition) {
      throw new Error(`Unsupported host: ${host}. Use --host node, python, or codex.`);
  }

  if (definition.generatedReadme) {
    return definition;
  }

  return HOST_DEFINITIONS[definition.canonicalHost];
}

function resolveTemplateSourceDir(sourceDirName: string): string {
  return path.join(__dirname, "..", "examples", sourceDirName);
}

export function parseArgs(argv: string[]): InitConsumerCliArgs {
  const parsed: InitConsumerCliArgs = {
    host: null,
    outDir: null,
    force: false,
    help: false
  };

  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];

    if (token === "--host") {
      parsed.host = argv[index + 1] ?? null;
      index += 1;
      continue;
    }

    if (token === "--out") {
      parsed.outDir = argv[index + 1] ?? null;
      index += 1;
      continue;
    }

    if (token === "--force") {
      parsed.force = true;
      continue;
    }

    if (token === "--help" || token === "-h") {
      parsed.help = true;
    }
  }

  return parsed;
}

export function getUsageText(): string {
  return [
    "Usage: user-habit-pipeline-init-consumer --host <node|python|codex> --out <directory> [--force]",
    "",
    "Copy packaged external-consumer starter files into a target project directory.",
    "",
    "Options:",
    "  --host <node|python|codex>  Required host family to scaffold.",
    "  --out <directory>     Required target directory for the generated starter files.",
    "  --force               Overwrite generated files if they already exist.",
    "  --help, -h            Show this help text."
  ].join("\n");
}

function printUsageAndExit(code: number, stream: NodeJS.WriteStream = process.stdout): never {
  stream.write(`${getUsageText()}\n`);
  process.exit(code);
}

export function validateArgs(args: InitConsumerCliArgs): void {
  if (!args.host || !String(args.host).trim()) {
    throw new Error("--host requires a target host. Use node, python, or codex.");
  }

  if (!args.outDir || !String(args.outDir).trim()) {
    throw new Error("--out requires a target directory.");
  }
}

export function writeConsumerTemplateFiles(
  host: string,
  outDir: string,
  force: boolean = false
): WriteConsumerTemplateResult {
  const definition = getCanonicalHostDefinition(host);
  const resolvedOutDir = path.resolve(process.cwd(), outDir);
  const templateSourceDir = resolveTemplateSourceDir(definition.sourceDirName);

  if (!fs.existsSync(templateSourceDir)) {
    throw new Error(`Template source directory not found: ${templateSourceDir}`);
  }

  fs.mkdirSync(resolvedOutDir, { recursive: true });

  const writtenFiles: string[] = [];
  const generatedReadmePath = path.join(resolvedOutDir, "README.md");

  if (!force && fs.existsSync(generatedReadmePath)) {
    throw new Error(`Refusing to overwrite existing file: ${generatedReadmePath}. Use --force to replace generated files.`);
  }

  fs.writeFileSync(generatedReadmePath, `${definition.generatedReadme}\n`, "utf8");
  writtenFiles.push(generatedReadmePath);

  for (const filename of definition.filenames) {
    const sourcePath = path.join(templateSourceDir, filename);
    const targetPath = path.join(resolvedOutDir, filename);

    if (!fs.existsSync(sourcePath)) {
      throw new Error(`Template source file not found: ${sourcePath}`);
    }

    if (!force && fs.existsSync(targetPath)) {
      throw new Error(`Refusing to overwrite existing file: ${targetPath}. Use --force to replace generated files.`);
    }

    fs.copyFileSync(sourcePath, targetPath);
    writtenFiles.push(targetPath);
  }

  return {
    ok: true,
    host: definition.canonicalHost,
    out_dir: resolvedOutDir,
    files: writtenFiles
  };
}

export function main(argv: string[] = process.argv.slice(2)): void {
  const args = parseArgs(argv);
  if (args.help) {
    printUsageAndExit(0, process.stdout);
  }

  try {
    validateArgs(args);
    const result = writeConsumerTemplateFiles(args.host as string, args.outDir as string, args.force);
    process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    process.stderr.write(`${message}\n`);
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}
